fruits=["apples","bananas","pears"]
print (fruits)
fruits.append("mango")
print (fruits)
fruits.insert(2,"kiwi")
print (fruits)
fruits.remove("pears")
print(fruits)
del fruits [0]
print (fruits)
n=len(fruits)
print (n)
colors= ("red","orange","yellow","green","blue")
print (colors)
colors=list (colors)
colors.append ("pink")
colors=tuple (colors)
print (colors)
fruits=tuple (fruits)
